name: Test

on:
  push:
    branches:
      - main

jobs:
  test-js-runtime:
    name: Test js_runtime on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: packages/core/js_runtime
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.4'
      - run: flutter pub get
      - run: sh test/integration_test_macos.sh
