name: Test

on:
  push:
    branches:
      - master

jobs:
  test-js-runtime:
    name: Test js-runtime on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./packages/core/js-runtime
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Update submodules
        run: git submodule update --init --recursive
      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.4'
      - run: flutter pub get
      - run: sh test/integration_test_android.sh
